### ISSUE TITLE
Where can i find the Localhost port?

### ISSUE THREAD

**Issue by jesraygarciano** [robbinworks/sage-laravel-mix#1]
## Submit a feature request or bug report
I'd like to know the localhost port when running the laravel mix if there are any. Thank you

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/robbinfellow/sage-laravel-mix/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

X

**What is the expected or desired behavior?**

X

---

## Bug report

**Please provide steps to reproduce, including full log output:**

X

**Please describe your local environment:**

WordPress version: X

OS: X

NPM/Node version: X

**Where did the bug happen? Development or remote servers?**

X

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by robbinworks** [comment]
Laravel mix is running on port `8080` and is configurable using `mix.options()`, eg:

```
mix.options({
    hmrOptions: {
        host: 'localhost',
        port: 8089
    }
})
```

Full documentation available [here](https://laravel-mix.com/docs/), make sure you read docs from the same version of mix you're using. 

Good luck!

**Comment by jesraygarciano** [comment]
Thank you.
